### ISSUE TITLE
treestore crashes when creating any table

### ISSUE THREAD

**Issue by greenlion** [tjizep/treestore#10]
I downloaded 5.6.20 from the MySQL archive.  After installing the plugin (which installs successfully) I get the following in the error log:
2015-02-19 00:00:21 10886 [Warning] Storage engine 'TREESTORE' has conflicting typecode. Assigning value 42.

-- the following crashes the server
set default_storage_engine=treestore;
CREATE TABLE t1 (c1 int);

Here is the resolved stack trace:
0x6724b8 handle_fatal_signal + 984
0x7fd5ef42f130 _end + -301317088
0x7fd5ee066ba1 _end + -322060655
0x7fd5ee9874c5 _end + -312490059
0x7fd581b54c28 _end + -2139316456
0x59337d _Z15ha_create_tableP3THDPKcS2_S2_P24st_ha_create_informationbb + 541
0x794b96 _Z16rea_create_tableP3THDPKcS2_S2_P24st_ha_create_informationR4ListI12Create_fieldEjP6st_keyP7handlerb + 294
0x740041 _Z17create_table_implP3THDPKcS2_S2_P24st_ha_create_informationP10Alter_infobjbPbPP6st_keyPj + 2545
0x740988 _Z26mysql_create_table_no_lockP3THDPKcS2_P24st_ha_create_informationP10Alter_infojPb + 312
0x740ef8 _Z18mysql_create_tableP3THDP10TABLE_LISTP24st_ha_create_informationP10Alter_info + 168
0x6f71ce _Z21mysql_execute_commandP3THD + 25966
0x6f7c58 _Z11mysql_parseP3THDPcjP12Parser_state + 792
0x6f8fab _Z16dispatch_command19enum_server_commandP3THDPcj + 3019
0x6fada7 _Z10do_commandP3THD + 215
0x6c2d26 _Z24do_handle_one_connectionP3THD + 278
0x6c2e05 handle_one_connection + 69
0x9802b6 pfs_spawn_thread + 294
0x7fd5ef427df3 _end + -301346589
0x7fd5ee0d63dd _end + -321603891

**Comment by tjizep** [comment]
It looks like a old version, is it on linux or windows ? I cant replicate it by the way

**Comment by tjizep** [comment]
Ive used this version mysql-5.6.20-winx64

**Comment by greenlion** [comment]
Hi,

It is on linux.  I downloaded the 5.6.20 tarball, extracted to
/usr/local/mysql, copied treestore.so from the repo to
/usr/local/mysql/lib/plugin, then installed the plugin.

Creating any treestore table crashes, and accessing any database that has a
crashed table also crashes.

**Comment by tjizep** [comment]
It's related to the build in Linux I have to fix it

**Comment by greenlion** [comment]
ok.  let me know when it is fixed and I'll test it out.

--Justin

**Comment by tjizep** [comment]
added fixed build to repository
