### ISSUE TITLE
Please provide Linux build instructions

### ISSUE THREAD

**Issue by greenlion** [tjizep/treestore#9]
When I try to install the plugin I get this:
mysql> INSTALL PLUGIN TREESTORE SONAME 'libtreestore.so';
ERROR 1126 (HY000): Can't open shared library '/usr/lib64/mysql/plugin/libtreestore.so' (errno: 2 /usr/lib64/mysql/plugin/libtreestore.so: undefined symbol: _ZTI7handler)

I guess it is because my MySQL is a different version than it was compiled for.  

I'd like to build the plugin myself, but there is no Makefile, not automake script to generate one and no CMake files either.  How does it build with GCC without a build system?

**Comment by greenlion** [comment]
I installed Code::Blocks, and tried to build the project but the build fails:
||=== Build: ReleaseDebug Win32 in treestore (compiler: GNU GCC Compiler) ===|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\lz4-r101\lz4.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\adler32.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\compress.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\crc32.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\deflate.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\infback.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\inffast.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\inflate.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\inftrees.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\trees.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\uncompr.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\..\repo\zlib-1.2.8\zutil.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\repo\fse\fse.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\repo\fse\zlibh.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\abstracted_storage.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\collumn.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\fields.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\journal.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\MurmurHash3.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\myi.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\persist_tree.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Data\SQLite\src\sqlite3.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_chartables.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_compile.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_exec.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_fullinfo.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_globals.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_maketables.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_newline.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_ord2utf8.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_study.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_tables.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_try_flipped.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_ucd.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_valid_utf8.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\poco-1.4.6p1-all\Foundation\src\pcre_xclass.c|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\stx\btree.cpp|
||WARNING: Can't read file's timestamp: /home/justin/treestore/treestore/..\src\transactional_storage.cpp|
/home/justin/treestore/treestore/dllmain.cpp|6|fatal error: Poco/Mutex.h: No such file or directory|
||=== Build failed: 1 error(s), 38 warning(s) (0 minute(s), 0 second(s)) ===|

Is there a setting in the GUI that I have to change to build the project?

**Comment by tjizep** [comment]
I'll get on it soon

**Comment by tjizep** [comment]
linux build instructions have been added
